### PR TITLE
Add blank blog, contacts, and courses pages with consistent navbar

### PR DESCRIPTION
**Pull request by tejasbenibagde**
This pull request adds three new blank pages to the project with a consistent navbar layout across all of them.

Changes:

- `Blog Page`: Added a /blog route with a blank page and the same navbar as the rest of the site.
- `Contacts Page`: Added a /contacts route with a blank page and consistent navbar.
- `Courses Page`:Added a /courses route with a blank page and consistent navbar.

Purpose of the Changes:

These pages serve as placeholders for future content. The navbar across all pages ensures that the structure remains consistent for future development.

Next Steps:

- Add actual content to the pages.
- Style each page to align with the overall design of the site.

Let me know if you need any adjustments or further changes!

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@tejasbenibagde Can you add some screenshot as it difficult to see changes

**Comment by tejasbenibagde** [comment]
Hi, @PriyaGhosal 

I understand the request for screenshots, but I believe the changes can be effectively communicated through the explanation provided.

In this PR, I've added three blank pages: Blog, Contacts, and Courses, each featuring your original navbar and a preloader. The key enhancement is that we can now navigate through these different routes, improving the site's structure and functionality.

These pages are placeholders for future content, allowing us to start working on them as needed.

If you still think screenshots are necessary, I can provide them. Let me know if you have any further questions!

**Comment by tejasbenibagde** [comment]
also I'm not working on some specific issue but my Pull Request definetly solves the issue no #37

**Comment by PriyaGhosal** [comment]
@tejasbenibagde Great contribution to HACKTOBERFEST'24! 🎉

**Comment by tejasbenibagde** [comment]
Thank you for merging my PR. Please let me know if you want my help at something.

**Pull request merged**
