### PR TITLE
Changed nav logo to circle 

### PR DESCRIPTION
**Pull request by swamimalode07**

### CODE REVIEW

**Comment by swamimalode07** [comment]
Kindly merge this issue for hactober fest

**Comment by swamimalode07** [comment]
Please merge this changes , it does not conflict with the base branch

**Comment by PriyaGhosal** [comment]
Resolved merge conflicts: There were conflicts when merging recent updates. Look into it and resolve it asap


image

**Comment by swamimalode07** [comment]
Can you please check it now
i have resolved the conflicts

**Comment by swamimalode07** [comment]
pleasse merge this request

**Comment by PriyaGhosal** [comment]
image
@swamimalode07 Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
