### PR TITLE
Updated Copyright page added Dark mode #120

### PR DESCRIPTION
**Pull request by DhruvJohri**
Hello @PriyaGhosal 

I have updated copyright page as per the need of the project added all the necessary details and added the Dark Mode as per need , Please merge my PR under the HACKTOBERFEST 2024 Label so that it is counted as a contribution and I have resolved the conflict this time.
Screenshot 2024-10-09 115134

Regards
Dhruv Johri

### CODE REVIEW

**Comment by DhruvJohri** [comment]
Hello @PriyaGhosal 
I have resolved all the conflicts please check
nn

**Comment by DhruvJohri** [comment]
Hoping to get it merge under hacktoberfest 2024 this time @PriyaGhosal

**Comment by PriyaGhosal** [comment]
@DhruvJohri 
image
Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Comment by DhruvJohri** [comment]
But no conflict is shown when I raised my pr please see the above pic @PriyaGhosal

**Comment by DhruvJohri** [comment]
Please check this @PriyaGhosal

**Comment by DhruvJohri** [comment]
Nothing is showing on my pr page this time @PriyaGhosal

**Comment by DhruvJohri** [comment]
Please help to resolve this issue @PriyaGhosal

**Pull request closed without merging**
