### PR TITLE
Added counter feature

### PR DESCRIPTION
**Pull request by lord-cyclone100**
issue #32 
I have added the counter

--------
Before
--------
Screenshot (9)

--------
After
--------
Screenshot 2024-10-01 001607
Screenshot 2024-10-01 001558
Screenshot 2024-10-01 001540
Screenshot 2024-10-01 001511
Screenshot (10)

https://github.com/user-attachments/assets/5a57e5ef-0ac0-4e95-8f1d-e83354b35b21

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@lord-cyclone100 Please look into issues and resolve it 
image

**Comment by lord-cyclone100** [comment]
@PriyaGhosal 
Should I open a new pr?

**Comment by lord-cyclone100** [comment]
@PriyaGhosal 
check pls...i have resolved the issues

**Comment by lord-cyclone100** [comment]
issue #44
@PriyaGhosal

**Comment by PriyaGhosal** [comment]
@lord-cyclone100 Website has Dark and night mode which is not getting enabled after adding your issue .. Make a new issue with proper sync folk

**Pull request closed without merging**
