### PR TITLE
feat: add contact page using email js 

### PR DESCRIPTION
**Pull request by realvishalrana**
before
image

after 
image

Please merge the pull request after 1st Oct

### CODE REVIEW

**Comment by realvishalrana** [comment]
@PriyaGhosal Please check for feat: add contact page using email js

**Comment by realvishalrana** [comment]
https://github.com/PriyaGhosal/SkillWise/issues/20

this issue done

**Comment by realvishalrana** [comment]
@PriyaGhosal Please review #38 and merge it

**Comment by PriyaGhosal** [comment]
@realvishalrana Great contribution to HACKTOBERFEST'24! 🎉

**Pull request merged**
