### PR TITLE
Contributed to the resolution of issues #239 and #242  by adding Terms and Condition page and Privacy Policy 

### PR DESCRIPTION
**Pull request by SACHINkgu**
Description:
 - The page has been seamlessly integrated into the main index page, ensuring easy access for all users and enhancing overall navigation."
 -  A Terms & Conditions page provides users with essential information regarding their rights and responsibilities while using the platform.

### CODE REVIEW

**Comment by SACHINkgu** [comment]
image

**Comment by SACHINkgu** [comment]
Aso added Privacy Policy page :
image

**Comment by SACHINkgu** [comment]
Thank you
Kindly , make this contribution as part of Hacktoberfest 2024 .

**Comment by SACHINkgu** [comment]
Hello! @PriyaGhosal ji .
I have sent you my pull request please check it out , I hope you merge it , thank you.

**Comment by PriyaGhosal** [comment]
@SACHINkgu Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor.
Great contribution to HACKTOBERFEST'24! 🎉

**Pull request merged**
