### PR TITLE
feat: Added skeleton screen loading for home page

### LINKED ISSUE #850: feat : Add skeleton loading screen for home page

### PR DESCRIPTION
**Pull request by AryanGupta001**
### Title of the Pull Request
- [x] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #850 
### Description
This PR introduces a skeleton loading screen for the homepage, improving the user experience by showing placeholder elements while the content is loading. 

### Type of change

What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@AryanGupta001 
image
Please see the conflicts .

**Comment by PriyaGhosal** [comment]
@AryanGupta001 Are you working on it... as today is the last date of hacktoberfest 2024

**Comment by AryanGupta001** [comment]
> @AryanGupta001 Are you working on it... as today is the last date of hacktoberfest 2024
Yes. I will rectify and update the PR.

**Comment by AryanGupta001** [comment]
I have corrected it.

**Comment by PriyaGhosal** [comment]
@AryanGupta001 Great contribution ! 🎉 Your pull request has been successfully merged! Also Take a moment to ⭐ Star the repository if you haven't already.

**Pull request merged**
