### PR TITLE
Fixes: #512 Made the Navbar Responsive for all display Sizes 

### PR DESCRIPTION
**Pull request by MOHIT-IITP**
Fixes: #512 
Made the Navbar responsive for all display sizes . 
- [x] Have you renamed the PR Title in a meaningful way?
Before: It was overlapping 
Screenshot 2024-10-15 at 4 50 20 PM

After:

https://github.com/user-attachments/assets/3f407f2c-bc91-4aa2-a071-9651b8e1ab8d

### Type of change

What sort of changes have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [ x] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by MOHIT-IITP** [comment]
@PriyaGhosal  i have resolve all the conflicts , no you can merge it . 👍

**Comment by PriyaGhosal** [comment]
@MOHIT-IITP 
image
This is current navbar ... Please modify this

**Comment by MOHIT-IITP** [comment]
@PriyaGhosal  I have modified navbar  with the latest change

**Comment by PriyaGhosal** [comment]
@MOHIT-IITP Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. You can also contribute in my another Repository BuddyTrail which is also under Hacktoberfest
Great contribution to HACKTOBERFEST'24! 🎉

**Pull request merged**
