### PR TITLE
feat: Adjusted button smoother UI experience

### PR DESCRIPTION
**Pull request by sohelhussain**
perf:     Enhanced button UI, tailored to match the theme of your website.

### Description
Refined the button UI to better align with the website’s overall theme. Adjusted colors, padding, and typography to ensure a cohesive design while enhancing the user experience. Incorporated smooth transitions, subtle hover effects, and modern aesthetics to make the button visually appealing and interactive, providing a polished and consistent look across the site.

This description highlights the specific improvements and the reasoning behind the changes.

### Before
Screenshot 2024-10-22 at 7 49 50 AM

### After

Screenshot 2024-10-22 at 8 36 03 AM

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@sohelhussain Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch.

**Comment by PriyaGhosal** [comment]
@sohelhussain  Please see the conflicts . Resolve the conflicts .

**Comment by sohelhussain** [comment]
@PriyaGhosal Sorry, I can’t see your message.

**Comment by anuragverma108** [comment]
@sohelhussain Good Work!

**Pull request merged**
