### PR TITLE
Done

### PR DESCRIPTION
**Pull request by Swastik200**
ISSUE #48 
DONE 
PLZ CHECK AND CONFIRM

BEFORE

AFTER

### CODE REVIEW

**Comment by Swastik200** [comment]
Done please check

**Comment by Swastik200** [comment]
Added GITHUB PROFILE NAVIGATOR
Issue #71 
Please check and merge

**Comment by PriyaGhosal** [comment]
@Swastik200 Where is it in SkillWise website

**Comment by Swastik200** [comment]
Actually I'm not able to create another new pull request can I add it it
another existing forks so that you can merge it please?

**Comment by Swastik200** [comment]
Will do it

**Comment by Swastik200** [comment]
issue #71 done
Output 

https://github.com/user-attachments/assets/ba40d486-3a33-4e9b-88d6-0838bc758642

Please check and confirm

**Comment by Swastik200** [comment]
Done #72 
Please check and confirm

https://github.com/user-attachments/assets/882cb49e-d121-4bbd-88e4-b3ba69f26c4b

**Comment by Swastik200** [comment]
plz check and confirm

**Comment by Swastik200** [comment]
I had attached 3 codes with screenshot proof
Please check once and confirm
Don't close

**Pull request closed without merging**
