### PR TITLE
 #4 Landing Page : Removed one extra button

### PR DESCRIPTION
**Pull request by codeforlifeee**
image
Removed One Extra Button

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@codeforlifeee 
Please note that this is not in line with our code of conduct. To ensure clarity and proper assignment tracking, you need to create issue with proper issue number

**Comment by PriyaGhosal** [comment]
@codeforlifeee 
Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. This issue was raised by someone else. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by codeforlifeee** [comment]
when this will be merged?

**Comment by PriyaGhosal** [comment]
@codeforlifeee Great contribution to HACKTOBERFEST'24! 🎉

**Comment by codeforlifeee** [comment]
@PriyaGhosal please add hacktoberaccepted tag to this one...

**Comment by codeforlifeee** [comment]
image
 I have successfully merged two pull requests but still the count isnot increasing ..can you plz help me out with this @PriyaGhosal

**Pull request merged**
