### PR TITLE
Added Dark mode to look more attractive .

### PR DESCRIPTION
**Pull request by ankit071105**
# Description: This pull request introduces a dark mode feature to the website, allowing users to toggle between light and dark themes for a more comfortable viewing experience in low-light environments.

# Key Features:
Dark Mode Toggle:

A new toggle button has been added to switch between light and dark themes.
The dark mode theme includes a color palette designed to reduce eye strain (darker background, lighter text, and adjusted button colors).
The user's theme preference is saved using localStorage, ensuring the selected mode persists across page reloads and future sessions.
Smooth Transitions:

CSS transitions have been added to create a smooth, visually appealing effect when switching between light and dark modes.
# How It Works:
CSS Variables: Dark and light mode colors are defined using CSS variables for easy theming.
JavaScript: A script handles the toggle functionality and stores the user's preference in localStorage.
Animations: Subtle animations enhance the visual experience when interacting with the dark mode toggle.
Testing:
Tested across various browsers and screen sizes to ensure compatibility and responsiveness.
Verified that the dark mode preference is saved and correctly applied on page reload.

# Video 

https://github.com/user-attachments/assets/65f8dd23-fe20-4fb2-b67d-28eb90c0bc30

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@ankit071105 Some conflicts are reflecting .Look Into it asap 
image

**Comment by ankit071105** [comment]
Resolved the conflicts @PriyaGhosal

**Comment by ankit071105** [comment]
Resolved the conflicts @PriyaGhosal You can merge the pull request

**Comment by PriyaGhosal** [comment]
@ankit071105 Great contribution to HACKTOBERFEST'24! 🎉

**Pull request merged**
