### PR TITLE
Making footer consistent throughout website

### PR DESCRIPTION
**Pull request by Darpana-iitgn**
### Title of the Pull Request
- [x] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #<851>

### Description

Homepage: 
image

FAQs page: 
image

Opportunities page: 
image

### Type of change

What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [x] My code follows the code style of this project.
- [x] I have followed the contribution guidelines
- [x] I have performed a self-review of my own code.
- [x] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [x] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@Darpana-iitgn Please see the conflicts .

**Comment by PriyaGhosal** [comment]
@Darpana-iitgn Are you working on it... as today is the last date of hacktoberfest 2024

**Comment by Darpana-iitgn** [comment]
Yes I am checking it

**Comment by Darpana-iitgn** [comment]
@PriyaGhosal There are no conflicts now so you can merge this PR

**Comment by PriyaGhosal** [comment]
@Darpana-iitgn Great contribution ! 🎉 Your pull request has been successfully merged! Also Take a moment to ⭐ Star the repository if you haven't already.

**Pull request merged**
