### PR TITLE
icon changed #78

### PR DESCRIPTION
**Pull request by yeshwanth-ds**
Icon changed successfully

Before :
Screenshot 2024-10-01 223740

After:
Screenshot 2024-10-01 233746

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@yeshwanth-ds Change the datascience logo with finance one and add something else for datascience
image

**Comment by yeshwanth-ds** [comment]
@PriyaGhosal Sure!!

**Comment by yeshwanth-ds** [comment]
@PriyaGhosal Actually the Data Scienece coloum is created twice , Both the first block and fourth block has the same name "Data science". Do you have any recomendation for the name changing. I would recomment to add "Digital Marketing" to one of the block. If "Digital Marketing" please let me know.
Screenshot 2024-10-02 001641

**Comment by yeshwanth-ds** [comment]
@PriyaGhosal  icons changed sucessfully.
Before
Screenshot 2024-10-02 011755
After
Screenshot 2024-10-02 011523

**Comment by yeshwanth-ds** [comment]
@PriyaGhosal i will be closing this, so that i can work on a new issue

**Pull request closed without merging**
