### PR TITLE
Issue regarding menu links #1

### PR DESCRIPTION
**Pull request by roiveredritesh**
Changes in index.html and script.js for menu links

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@roiveredritesh  Please look into the issues
image

**Comment by roiveredritesh** [comment]
Before merging the PR. Please make sure is there any unnecessary files are not present there like node_modules and other files.

**Comment by PriyaGhosal** [comment]
image
@roiveredritesh Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Comment by roiveredritesh** [comment]
@PriyaGhosal Could you please let me know why you closed this PR?

**Pull request closed without merging**
