### PR TITLE
fix: 🐛 Improved Documentation

### PR DESCRIPTION
**Pull request by yashksaini-coder**
✅ Closes: #118

This pull request includes significant updates to the `README.md` file to enhance its structure, readability, and comprehensiveness. The most important changes include reformatting the introduction, adding visual elements, expanding the features section, and providing detailed instructions for getting started and contributing.

### Enhancements to `README.md`:

* Reformatting and Visual Enhancements:
  - Centered the title and added an image for visual appeal. (`README.md` [README.mdL1-R131](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R131))
  - Included a table with GitHub repository statistics such as stars, forks, issues, and pull requests. (`README.md` [README.mdL1-R131](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R131))

* Expanded Content:
  - Added a detailed features section highlighting key aspects like interactive courses, expert instructors, a supportive community, and personalized learning paths. (`README.md` [README.mdL1-R131](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R131))
  - Introduced a prerequisites section listing necessary tools and software for running the project. (`README.md` [README.mdL1-R131](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R131))
  - Provided a comprehensive "Getting Started" section with step-by-step instructions for new users. (`README.md` [README.mdL1-R131](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R131))

* Contribution Guidelines:
  - Detailed instructions for contributing to the project, including forking the repository, cloning it locally, creating branches, making changes, and submitting pull requests. (`README.md` [README.mdL1-R131](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R131))

These changes aim to improve user engagement and ease the onboarding process

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@PriyaGhosal Check this PR and also add labels to it.

**Comment by yashksaini-coder** [comment]
@PriyaGhosal Can you review this PR as it will be the base for the upcoming feature integration i.e, #237

**Comment by PriyaGhosal** [comment]
@yashksaini-coder 
image
Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Comment by yashksaini-coder** [comment]
Okh @PriyaGhosal

**Pull request closed without merging**
